### ISSUE TITLE
Can not find example file: --gmt_file 

### ISSUE THREAD

**Issue by LDHHAHA** [opain/TWAS-GSEA#1]
Hi @opain ,i had completed the Predicting TWAS features (FeaturePred). When i run the GSEA example data, i could not find your gmt_file. So i download the gmt file from msigdb(http://www.gsea-msigdb.org/gsea/downloads.jsp),msigdb.v7.4.entrez.gmt. but it did not work.
the code and the error:
Rscript TWAS-GSEA.V1.0.R \
> --twas_results ukbiobank-2017-1160-prePRS-fusion.tsv.GW \
> --pos CMC.BRAIN.RNASEQ.pos \
> --gmt_file ./GSEA.input/msigdb.v7.4.entrez.gmt \
> --expression_ref CMC.BRAIN.RNASEQ_GeneX_all_MINI.csv \
> --output demo
Error in getopt_options(object, args) : 
  Error in getopt(spec = spec, opt = args) : long flag "pos" is invalid
Calls: parse_args -> parse_options -> getopt_options
Execution halted.

look forward for your help.
Thanks.

**Comment by opain** [comment]
Hello @LDHHAHA,

Apologies, I believe this is due to changes in TWAS-GSEA. Please use the latest version, TWAS-GSEA.V1.2.R. I was not very familiar with git when I set this repo up, hence having multiple versions in a github repo. I have now removed the old versions of TWAS-GSEA, and changed the example code to use V1.2.

.gmt files from msigdb are the correct format.

Let me know if you still get the same error.

Best wishes,

Ollie
