### ISSUE TITLE
Error in order(...) : argument 1 is not a vector

### ISSUE THREAD

**Issue by MIAO0916** [opain/TWAS-GSEA#3]
Hello, thank you for your patience last time, I have another problem, can you help me to solve it?

My code looks like this：
`Rscript /home/jiangfeng/software/TWAS-GSEA/TWAS-GSEA.V1.2.R\
	--twas_results anno.cut_car_Boer_meta_82w_Cell2021.OA.hip.table.all \
	--pos OA_cartilage_v1.WH_fusion.P01.pos \
	--gmt_file c5.all.v2022.1.Hs.symbols.gmt \
	--expression_ref OA_cartilage_v1.WH_fusion_GeneX_all_MINI.csv \
	--output demo`

Their paths are all correct and the contents are respectively as follows：

1. --twas_results anno.cut_car_Boer_meta_82w_Cell2021.OA.hip.table.all：

FILE	ID	CHR	P0	P1	TWAS.Z	TWAS.P
/home/jiangfeng/project/TWAS-GSEA/OA_cartilage_v1.WH_fusion/ENSG00000156671.8.fusion_model.wgt.RDat	SAMD8	10	76859344	76941881	 0.7681	0.44242
/home/jiangfeng/project/TWAS-GSEA/OA_cartilage_v1.WH_fusion/ENSG00000150076.18.fusion_model.wgt.RDat	C10orf68	10	32832297	33171802	 1.6399	0.10102

2. --pos OA_cartilage_v1.WH_fusion.P01.pos ：
WGT	ID	CHR	P0	P1
OA_cartilage_v1.WH_fusion/ENSG00000001561.6.fusion_model.wgt.RDat	ENPP4	6	46097730	46114436
OA_cartilage_v1.WH_fusion/ENSG00000002016.12.fusion_model.wgt.RDat	RAD52	12	1021243	1099219

3. --expression_ref OA_cartilage_v1.WH_fusion_GeneX_all_MINI.csv：
FID     IID     ENSG00000040731.6       ENSG00000051596.5
HG00096 HG00096 0.28    -0.135
HG00097 HG00097 0.28    -0.135
NA20828 NA20828 -1.024  -0.135
NA20832 NA20832 0.28    -0.791

The error message is as follows：
**Error in order(...) : argument 1 is not a vector
Calls: [ ... order -> standardGeneric -> eval -> eval -> eval -> order
Execution halted**

The log file stops here：
TWAS contains 1643 unique features with non-missing TWAS.P values.

I currently suspect that the first is the format of --twas_results, and the second is the existence of NA's FID and IID in --expression_ref, but that's how FeaturePred is generated, do I need to remove NA's results?

If you can help me, I would be very grateful.

YOURS,
MIAO

**Comment by MIAO0916** [comment]
Today, I experimented with replacing the ENSG number with Gene symbol, and edited  --twas_results anno.cut_car_Boer_meta_82w_Cell2021.OA.hip.table.all  strictly according to the sample file FILE、P0、P1、TWAS Z，TWAS.P., but still got the same error

**Comment by MIAO0916** [comment]
Suddenly found that the .csv file is not separated by commas, and rushed to correct, and the FID and IID for the NA line are deleted, but the same error still reported.
now the contents of input files are:

1. --twas_results anno.cut_car_Boer_meta_82w_Cell2021.OA.hip.table.all：
FILE	P0	P1	TWAS.Z	TWAS.P
/home/jiangfeng/project/TWAS-GSEA//OA_cartilage_v1.WH_fusion/SAMD8.fusion_model.wgt.RDat	76859344	76941881	 0.90758	0.364103
/home/jiangfeng/project/TWAS-GSEA//OA_cartilage_v1.WH_fusion/C10orf68.fusion_model.wgt.RDat	32832297	33171802	 2.15871	0.030873

2. --pos OA_cartilage_v1.WH_fusion.P01.pos ：
WGT	ID	CHR	P0	P1
OA_cartilage_v1.WH_fusion/ENPP4.fusion_model.wgt.RDat	ENPP4	6	46097730	46114436
OA_cartilage_v1.WH_fusion/RAD52.fusion_model.wgt.RDat	RAD52	12	1021243	1099219

3.--expression_ref OA_cartilage_v1.WH_fusion_GeneX_all_MINI.csv：
FID,IID,CDH10,THOC3,PRDM6
HG00096,HG00096,0.28,-0.135,0.627
HG00097,HG00097,0.28,-0.135,-1.301
HG00099,HG00099,-1.098,-0.791,-3.229
HG00101,HG00101,-1.098,2.028,0.627

When i rying to run the sample file, the error reported is：
`Error in biomartCacheClear() : 
  could not find function "biomartCacheClear"
Execution halted`

Rather different from mine, but still do not know how to solve.
I don't know where else to change my input file for a while，could you please help me?
yours,
MIAO

**Comment by opain** [comment]
Hello, 

Sorry for the slow reply.

I think the initial error is occurring because you do not have the 'MODELCV.R2' column in your TWAS results file. If there is only one feature per gene, then you can set the '--allow_duplicate_ID' parameter to 'F'. Otherwise the script tries to select a single most predictive feature per gene. Sorry this is not clear in the documentation. I think I understood your error by looking at when the 'order' function is used in the script after logging 'TWAS contains X unique features...'. 

The 'biomartCacheClear()' error might be due to using a different version of biomart. The function does exist: https://bioconductor.org/packages/devel/bioc/manuals/biomaRt/man/biomaRt.pdf. Perhaps try reinstalling. Apologies, nowadays I use conda environments to avoid these kinds of issues. I hope to revamp this repo in the future.

The best way to debug errors, is to open the R terminal, specify the 'opt' list using your parameters, and then running the script section by section.

Best wishes,

Ollie
